# Server config
server:
  servlet:
    context-path: /api

spring:

  # File config
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  # Database config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/docker_spring_restful
    username: postgres
    password: 1234

  # JPA config
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Jackson config
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

  # Flyway config
  flyway:
    url: jdbc:postgresql://localhost:5438/docker_spring_restful
    schemas: docker_spring_restful_schema
    user: postgres
    password: 1234
    locations: classpath:db/migration
    check-location: true
    baseline-on-migrate: true

# JWT config
security:
  jwt:
    secret-key: secret
    expire-lenght: 3600000

# SpringDoc config
springdoc:
  swagger-ui:
    path: /

# File config
file:
  upload-dir: /Users/Gabriel/Desktop/

# Log config
logging:
  file:
    name: startup.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      clean-history-on-start: true

