server:
  servlet:
    context-path: /api

spring:
  # Database config
  datasource:
    url: jdbc:h2:mem:restful
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always

  # JPA config
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

  # Jackson config
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

security:
  jwt:
    secret-key: secret
    expire-lenght: 3600000

# SpringDoc config
springdoc:
  swagger-ui:
    path: /

