spring:

  # File config
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  # Database config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-225-190-241.compute-1.amazonaws.com/df9d5l7msrhdh6
    username: bbsqfwsgtnjtaz
    password: bc9f8992c51b895ba686ea1e35de4fc6e5b244826638df008d032cb70fd6ec77

  # JPA config
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Jackson config
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

  # Flyway config
  flyway:
    url: jdbc:postgresql://ec2-54-225-190-241.compute-1.amazonaws.com/df9d5l7msrhdh6
    schemas: public
    user: bbsqfwsgtnjtaz
    password: bc9f8992c51b895ba686ea1e35de4fc6e5b244826638df008d032cb70fd6ec77
    locations: classpath:db/migration
    check-location: true
    baseline-on-migrate: true

# JWT config
security:
  jwt:
    secret-key: secret
    expire-lenght: 3600000

# SpringDoc config
springdoc:
  swagger-ui:
    path: /

# File config
file:
  upload-dir: /Users/Gabriel/Desktop/

# Log config
logging:
  file:
    name: startup.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      clean-history-on-start: true

doc:
  info:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

    contact:
      url: https://github.com/gabrielgoisandrade/
      name: Gabriel Gois Andrade
      email: gabriel.gois.andrade14@gmail.com

    license:
      url: https://www.apache.org/licenses/LICENSE-2.0.txt
      name: Apache License 2.0

    terms-of-service: http://springdoc.org/

  security:
    global-key: Access token
    scheme: bearer
    bearer-format: JWT
    description: Do auth, copy the token returned, and paste it here to unlock the others requests. It'll save your time! ;)

  server:
    description: Service hosted on heroku.
    url: https://spring-boot-restful.herokuapp.com/