CREATE TABLE IF NOT EXISTS docker_spring_restful_schema.TB_BOOK
(
    BOOK_ID     SERIAL PRIMARY KEY,
    TITLE       VARCHAR(100)   NOT NULL,
    AUTHOR      VARCHAR(50)    NOT NULL,
    PRICE       DOUBLE PRECISION NOT NULL,
    LAUNCH_DATE DATE           NOT NULL
);